#pragma config(Motor,  port2,           driveL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           driveR,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawL,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           clawR,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           seedDispense,  tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// globals
int leftX = 0;
int leftY = 0;
int rightY = 0;
int rightX = 0;
int thresh = 15;

const bool on = true;

task drive() { // L R drive
	while(on) {
		motor[driveL] = -rightY - rightX;
		motor[driveR] = rightY - rightX;
	}
} // end task drive

task manipulator() {

	motor [clawL] = 100;
	motor [clawR] = -100;
	motor [seedDispense] = 100;

	while(on){
		motor[arm] = leftY; // arm motor

		if(vexRT[Btn7L]) {
			motor[clawL] = 127;
			motor[clawR] = -127;
			} else if(vexRT[Btn7R]) {
			motor[clawL] = 0;
			motor[clawR] = -0;
		}

		if(vexRT[Btn7U]) {
			motor[seedDispense] = 127;
		}else if (vexRT[Btn7D]) {
			motor[seedDispense] = -127;
	  }
} // end while
} // end task manip

task main() { //This holds the main tasks the robot initially starts with.
startTask(drive);
startTask(manipulator);
while(on) {
	rightX = vexRT(Ch1);
	if(abs(rightX)<thresh){ //This adds a deadzone in the controller's right X axis
		rightX = 0;
	}
	rightY = vexRT(Ch2);
	if(abs(rightY)<thresh){ //This adds a deadzone in the controller's right Y axis
		rightY = 0;
	}
	leftY = vexRT(Ch3);
	if(abs(leftY)<thresh){ //This adds a deadzone in the controller's left Y axis
		leftY = 0;
	}
	leftX = vexRT(Ch4);
	if(abs(leftX)<thresh){ //This adds a deadzone in the controller's left X axis
		leftX = 0;
	}
}
} // end main
